
- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: Enable rag-api service
  systemd:
    name: rag-api
    enabled: true
    state: started
  become: true

- name: Restart rag-api service
  systemd:
    name: rag-api
    state: restarted
  become: true